name: pypi-release

on: push

jobs:
    build:
        name: Build distribution 📦
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.x"
        - name: install pypa/build
          run: >-
            python3 -m
            pip install build --user
        
        # package & store artifacts
        - name: package the pypi
          run: |
            cd tools && python3 -m build
        - name: store the distribution packages
          uses: actions/upload-artifact@v3
          with:
            name: python-package-distributions
            path: tools/dist/
    
    publish-to-pypi:
        name: Publish Python 🐍 distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
        needs:
        - build
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/malloctag-tools
        permissions:
            id-token: write  # IMPORTANT: mandatory for trusted publishing

        steps:
        - name: Download all the dists
          uses: actions/download-artifact@v3
          with:
            name: python-package-distributions
            path: tools/dist/
        - name: Publish distribution 📦 to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
